title: Mui(無為) Documentation
description: A Vim-like TUI text editor written in Ruby
baseurl: "/mui"
url: "https://s-h-gamelinks.github.io"

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

permalink: pretty

aux_links:
  GitHub: https://github.com/S-H-GAMELINKS/mui
  RubyGems: https://rubygems.org/gems/mui

nav_external_links:
  - title: GitHub
    url: https://github.com/S-H-GAMELINKS/mui

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2025 S-H-GAMELINKS. Distributed under the <a href=\"https://opensource.org/licenses/MIT\">MIT License</a>."

last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/S-H-GAMELINKS/mui"
gh_edit_branch: "master"
gh_edit_source: docs
gh_edit_view_mode: "edit"

callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
